In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv('F:/play_data.csv')
data

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [2]:
# CODE TO  CONVERT STRING VALUES TO INT
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["outlook"]=le.fit_transform(data["outlook"])
data["temp"]=le.fit_transform(data["temp"].astype(str))
data["humidity"]=le.fit_transform(data["humidity"].astype(str))
data["wind"]=le.fit_transform(data["wind"].astype(str))
data["play"]=le.fit_transform(data["play"].astype(str))
data

    day  outlook  temp  humidity  wind  play
0    D1        2     1         0     1     0
1    D2        2     1         0     0     0
2    D3        0     1         0     1     1
3    D4        1     2         0     1     1
4    D5        1     0         1     1     1
5    D6        1     0         1     0     0
6    D7        0     0         1     0     1
7    D8        2     2         0     1     0
8    D9        2     0         1     1     1
9   D10        1     2         1     1     1
10  D11        2     2         1     0     1
11  D12        0     2         0     0     1
12  D13        0     1         1     1     1
13  D14        1     2         0     0     0

In [3]:
X=data[['outlook','temp','humidity','wind']].values
y=data['play'].values

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30,random_state = 10)

In [5]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [6]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [7]:
y_pred = model.predict(X_test)
y_pred

array([1, 0, 1, 1, 0])

In [8]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

pred = model.predict(X_test)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[1 0]
 [1 3]]
              precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       1.00      0.75      0.86         4

    accuracy                           0.80         5
   macro avg       0.75      0.88      0.76         5
weighted avg       0.90      0.80      0.82         5

In [14]:
print('Accuracy of GNB classifier on test set: {:.2f}'.format(model.score(X_test, y_test)*100)+'%')

Accuracy of GNB classifier on test set: 80.00%

In [15]:
predicted= model.predict([[2,0,0,0]])
if predicted == 1:
  print("play Game")
else:
  print ("do not play Game")

do not play Game