In [2]:
import pandas as pd 
import numpy as np
data=pd.read_csv('F:/play_data.csv')
data

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['outlook'] = le.fit_transform(data['outlook'])
data['temp'] = le.fit_transform(data['temp'].astype(str))
data['humidity'] = le.fit_transform(data['humidity'].astype(str))
data['wind'] = le.fit_transform(data['wind'].astype(str))
data['play'] = le.fit_transform(data['play'].astype(str))
data

    day  outlook  temp  humidity  wind  play
0    D1        2     1         0     1     0
1    D2        2     1         0     0     0
2    D3        0     1         0     1     1
3    D4        1     2         0     1     1
4    D5        1     0         1     1     1
5    D6        1     0         1     0     0
6    D7        0     0         1     0     1
7    D8        2     2         0     1     0
8    D9        2     0         1     1     1
9   D10        1     2         1     1     1
10  D11        2     2         1     0     1
11  D12        0     2         0     0     1
12  D13        0     1         1     1     1
13  D14        1     2         0     0     0

In [4]:
x = data.iloc[:,1:5].values
y=data.iloc[:,5].values

In [5]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.fit_transform(xtest)

In [7]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=5)
model.fit(xtrain,ytrain)

KNeighborsClassifier()

In [8]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
ypred = model.predict(xtest)
print(classification_report(ytest,ypred))
print(confusion_matrix(ytest,ypred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.67      0.80         3

    accuracy                           0.67         3
   macro avg       0.50      0.33      0.40         3
weighted avg       1.00      0.67      0.80         3

[[0 0]
 [1 2]]

C:\Users\kanth\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [9]:
print("Acurracy {:.2f}".format(model.score(xtest,ytest)*100)+'%')

Acurracy 66.67%